stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: p-wpsrj:my-common-java
      version: 1.0.0
      answers:
        service.port: "8081"
      name: test
      targetNamespace: default
timeout: 60
notification: {}
