stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: p-wpsrj:my-mychart
      version: 0.1.0
      answers:
        service.port: "8080"
      name: test
      targetNamespace: default
timeout: 60
notification: {}
