stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.13.2
      shellScript: ' go build -o lingwei main.go'
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tibbersyu/localtest:${CICD_IMAGE_TAG}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-wpsrj:my-common-java
      version: 1.0.0
      answers:
        image.port: "8081"
        image.tag: ${IMAGE_TAG}
        name: ${APP_NAME}
        namespace: ${TARGET_NAMESPACE}
        service.port: "8081"
      name: mytest
      targetNamespace: default
timeout: 60
notification: {}
